name: CXNow
favicon: null
layout_spectrum: 0.49725
typography_spectrum: 0.22822
title: 'Ajatuksia verkosta, kaupasta, tulevaisuudesta ja asiakaskokemuksesta'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#000000'
    - '#b0b7af'
    - '#fea500'
    - '#683000'
  brandStrength: 1
  lightness: 0
  saturation: 0.5
  rhythmicContrast: 0
purpose: []
