typography_spectrum: 0.22822
color:
  brandColors:
    - '#ffffff'
    - '#000000'
    - '#b0b7af'
    - '#fea500'
    - '#683000'
  brandStrength: 1
  lightness: 0
  saturation: 0.5
  rhythmicContrast: 0
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.49725
analytics:
  google: null
  facebook: null
  twitter: null
name: CXNow
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: Kaupallisen Asiakaskokemuksen Chicago - IRCE osa 1
    id: b7e826c8-93f2-4b3d-9993-09dac730f523
    type: content
  - name: Yhtenäisen Tuotekokemuksen Chicago - IRCE osa 2
    id: ce65bd00-48be-47d2-a530-c04d2a2727c1
    type: content
favicon: null
title: Commercial Experience Now
description: 'Ajatuksia verkosta, kaupasta ja tulevaisuudesta'
purpose: []
